#!/usr/bin/env python3
"""
Parse and process KPI log files from the Android app.
"""

import pandas as pd
import numpy as np
from pathlib import Path
from typing import Optional, Tuple
from dataclasses import dataclass


@dataclass
class ColdStartMetrics:
    """Cold start timing metrics."""
    model_load_ms: float
    session_create_ms: float  # QNN compilation time
    first_inference_ms: float
    total_cold_ms: float


@dataclass
class KpiMetrics:
    """Aggregated KPI metrics from a benchmark run."""
    # Latency metrics (total E2E)
    latency_p50: float
    latency_p95: float
    latency_mean: float
    latency_std: float
    latency_min: float
    latency_max: float
    inference_count: int

    # E2E breakdown (P50)
    preprocess_p50: float       # Image preprocessing P50
    inference_only_p50: float   # Model inference only P50
    input_create_p50: float     # Input tensor creation (JNI boundary)
    output_copy_p50: float      # Output tensor copy (native → JVM)
    postprocess_p50: float      # NMS + coordinate transform P50
    detection_count_mean: float # Average detection count per frame

    # Throughput
    fps: float  # Inferences per second

    # Thermal drift metrics (for sustained performance analysis)
    first_30s_p50: float  # E2E Latency p50 in first 30 seconds
    last_30s_p50: float   # E2E Latency p50 in last 30 seconds
    drift_percent: float  # (last - first) / first * 100

    # Inference-only drift (session.run sustained behavior)
    infer_first_30s_p50: float  # Inference-only P50 in first 30 seconds
    infer_last_30s_p50: float   # Inference-only P50 in last 30 seconds
    infer_drift_percent: float  # (last - first) / first * 100

    # Thermal metrics
    thermal_start: float
    thermal_end: float
    thermal_max: float
    thermal_slope: float  # °C per minute

    # Power metrics
    power_mean: float
    power_std: float

    # Memory metrics
    memory_peak: int
    memory_mean: float
    memory_min: int
    memory_start: int    # first sample
    memory_end: int      # last sample

    # Duration
    duration_seconds: float

    # Cold start (optional, from metadata)
    cold_start: Optional[ColdStartMetrics] = None

    # ORT Profiling: NPU compute vs framework overhead (optional, from metadata)
    profiling_iterations: int = 0
    profiling_avg_total_ms: float = 0.0
    profiling_avg_npu_ms: float = 0.0
    profiling_avg_cpu_ms: float = 0.0
    profiling_avg_fence_ms: float = 0.0
    profiling_avg_overhead_ms: float = 0.0

    # Pipeline benchmark (optional, from metadata)
    pipeline_sequential_fps: float = 0.0
    pipeline_pipelined_fps: float = 0.0
    pipeline_speedup: float = 0.0
    pipeline_sequential_ms: float = 0.0
    pipeline_pipelined_ms: float = 0.0


def load_metadata(file_path: str) -> dict:
    """
    Extract metadata from comment lines in a KPI log CSV file.

    Args:
        file_path: Path to the CSV file

    Returns:
        Dict with metadata key-value pairs
    """
    metadata = {}
    with open(file_path, 'r', encoding='utf-8') as f:
        for line in f:
            if line.startswith('# '):
                parts = line[2:].strip().split(',', 1)
                if len(parts) == 2:
                    metadata[parts[0]] = parts[1]
            elif not line.startswith('#'):
                break  # Stop at data rows
    return metadata


def load_ort_log(csv_path: str) -> Optional[dict]:
    """
    Load ORT log file if it exists alongside CSV file.

    Args:
        csv_path: Path to the CSV file

    Returns:
        Dict with ORT log info or None if not found
    """
    import re

    # ORT log file has same name as CSV but with _ort.log suffix
    # e.g., kpi_YOLOv8n_QNNNPU_20260130_173916.csv -> kpi_YOLOv8n_QNNNPU_20260130_173916_ort.log
    log_path = Path(str(csv_path).replace('.csv', '_ort.log'))

    if not log_path.exists():
        return None

    try:
        with open(log_path, 'r', encoding='utf-8') as f:
            content = f.read()

        ort_info = {
            'raw_log': content,
            'total_nodes': 0,
            'qnn_nodes': 0,
            'cpu_nodes': 0,
            'fallback_ops': [],
            'qnn_error': None
        }

        # Parse summary section (header generated by app)
        for line in content.split('\n'):
            if 'Total nodes:' in line:
                try:
                    ort_info['total_nodes'] = int(line.split(':')[1].strip())
                except:
                    pass
            elif 'QNN nodes:' in line:
                try:
                    ort_info['qnn_nodes'] = int(line.split(':')[1].strip())
                except:
                    pass
            elif 'CPU fallback nodes:' in line:
                try:
                    ort_info['cpu_nodes'] = int(line.split(':')[1].strip())
                except:
                    pass
            elif 'Fallback ops:' in line:
                ops_str = line.split(':')[1].strip()
                if ops_str:
                    ort_info['fallback_ops'] = [op.strip() for op in ops_str.split(',')]

        # If summary has zero total nodes, parse from raw logs
        if ort_info['total_nodes'] == 0:
            # Reset counts to parse from raw logs
            ort_info['qnn_nodes'] = 0
            ort_info['cpu_nodes'] = 0

            for line in content.split('\n'):
                # Format A: "All nodes placed on [QNNExecutionProvider]. Number of nodes: 77"
                match = re.search(r'nodes placed on \[(\w+)\].*Number of nodes:\s*(\d+)', line)
                if match:
                    ep_name = match.group(1)
                    node_count = int(match.group(2))
                    ort_info['total_nodes'] += node_count
                    if 'QNN' in ep_name:
                        ort_info['qnn_nodes'] += node_count
                    elif 'CPU' in ep_name:
                        ort_info['cpu_nodes'] += node_count
                    continue

                # Format B (ORT 1.x): "GetCapability] Number of partitions supported by QNN EP: 1,
                #   number of nodes in the graph: 233, number of nodes supported by QNN: 233"
                # ORT calls GetCapability multiple times (per optimization pass); use the last value.
                match = re.search(
                    r'GetCapability.*number of nodes in the graph:\s*(\d+).*number of nodes supported by QNN:\s*(\d+)',
                    line, re.IGNORECASE
                )
                if match:
                    graph_count = int(match.group(1))
                    qnn_count = int(match.group(2))
                    ort_info['total_nodes'] = graph_count
                    ort_info['qnn_nodes'] = qnn_count
                    ort_info['cpu_nodes'] = graph_count - qnn_count

        # Parse fallback ops from raw logs
        # Example: "Validation FAILED for 1 nodes in NodeUnit (QuantizeLinear) :"
        for line in content.split('\n'):
            match = re.search(r'Validation FAILED.*NodeUnit\s*\(([^)]+)\)', line)
            if match:
                op = match.group(1)
                if op not in ort_info['fallback_ops']:
                    ort_info['fallback_ops'].append(op)

        # Always check for QNN errors in raw logs
        for line in content.split('\n'):
            if 'SetupBackend failed' in line or 'QNN_DEVICE_ERROR' in line or 'QNN_COMMON_ERROR' in line:
                error_match = re.search(r'Error:\s*([^,\n]+)', line)
                if error_match:
                    ort_info['qnn_error'] = error_match.group(1).strip()
                    break  # Only need first error

        return ort_info
    except Exception as e:
        print(f"Warning: Failed to load ORT log {log_path}: {e}")
        return None


def load_log(file_path: str) -> pd.DataFrame:
    """
    Load a KPI log CSV file.

    Args:
        file_path: Path to the CSV file

    Returns:
        DataFrame with parsed log data
    """
    # Skip comment lines starting with '#' (metadata)
    df = pd.read_csv(file_path, comment='#')

    # Convert timestamp to datetime
    df['datetime'] = pd.to_datetime(df['timestamp'], unit='ms')

    # Calculate relative time in seconds
    start_time = df['timestamp'].min()
    df['elapsed_seconds'] = (df['timestamp'] - start_time) / 1000.0

    return df


def split_events(df: pd.DataFrame) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """
    Split log into inference and system events.

    Args:
        df: Full log DataFrame

    Returns:
        Tuple of (inference_df, system_df)
    """
    inference_df = df[df['event_type'] == 'INFERENCE'].copy()
    system_df = df[df['event_type'] == 'SYSTEM'].copy()

    return inference_df, system_df


def calculate_metrics(df: pd.DataFrame, metadata: dict = None) -> KpiMetrics:
    """
    Calculate aggregated KPI metrics from a log file.

    Args:
        df: Full log DataFrame
        metadata: Optional metadata dict from CSV header

    Returns:
        KpiMetrics with calculated values
    """
    inference_df, system_df = split_events(df)

    # Latency metrics
    latencies = inference_df['latency_ms'].dropna()

    # Duration
    duration = df['elapsed_seconds'].max()

    # Throughput (FPS)
    fps = len(latencies) / duration if duration > 0 else 0

    # First 30s and Last 30s latency p50 (for thermal drift analysis)
    first_30s_latencies = inference_df[inference_df['elapsed_seconds'] <= 30]['latency_ms'].dropna()
    last_30s_latencies = inference_df[inference_df['elapsed_seconds'] >= duration - 30]['latency_ms'].dropna()

    first_30s_p50 = first_30s_latencies.quantile(0.50) if len(first_30s_latencies) > 0 else 0
    last_30s_p50 = last_30s_latencies.quantile(0.50) if len(last_30s_latencies) > 0 else 0

    # Inference-only drift (session.run sustained behavior)
    infer_first_30s_p50 = 0.0
    infer_last_30s_p50 = 0.0
    infer_drift_percent = 0.0
    if 'inference_ms' in inference_df.columns:
        first_30s_infer = inference_df[inference_df['elapsed_seconds'] <= 30]['inference_ms'].dropna()
        last_30s_infer = inference_df[inference_df['elapsed_seconds'] >= duration - 30]['inference_ms'].dropna()
        infer_first_30s_p50 = first_30s_infer.quantile(0.50) if len(first_30s_infer) > 0 else 0
        infer_last_30s_p50 = last_30s_infer.quantile(0.50) if len(last_30s_infer) > 0 else 0
        if infer_first_30s_p50 > 0:
            infer_drift_percent = (infer_last_30s_p50 - infer_first_30s_p50) / infer_first_30s_p50 * 100

    # Thermal metrics
    thermals = system_df['thermal_c'].dropna()
    thermal_times = system_df.loc[thermals.index, 'elapsed_seconds']

    # Calculate thermal slope (°C per minute)
    if len(thermals) >= 2:
        # Linear regression
        coeffs = np.polyfit(thermal_times / 60.0, thermals, 1)
        thermal_slope = coeffs[0]
    else:
        thermal_slope = 0.0

    # Power metrics
    powers = system_df['power_mw'].dropna()

    # Memory metrics
    memories = system_df['memory_mb'].dropna()

    # Cold start metrics from metadata
    cold_start = None
    if metadata:
        try:
            model_load = float(metadata.get('model_load_ms', 0))
            session_create = float(metadata.get('session_create_ms', 0))
            first_inf_str = metadata.get('first_inference_ms', 'N/A')
            first_inf = float(first_inf_str) if first_inf_str != 'N/A' else 0
            total_cold = float(metadata.get('total_cold_ms', 0))

            if model_load > 0 or session_create > 0:
                cold_start = ColdStartMetrics(
                    model_load_ms=model_load,
                    session_create_ms=session_create,
                    first_inference_ms=first_inf,
                    total_cold_ms=total_cold
                )
        except (ValueError, TypeError):
            pass

    # E2E breakdown metrics (handle old CSV format without these columns)
    has_breakdown = 'inference_ms' in inference_df.columns
    if has_breakdown:
        preprocess_times = inference_df['preprocess_ms'].dropna()
        inference_only_times = inference_df['inference_ms'].dropna()
        postprocess_times = inference_df['postprocess_ms'].dropna()
        detection_counts = inference_df['detection_count'].dropna()

        preprocess_p50 = preprocess_times.quantile(0.50) if len(preprocess_times) > 0 else 0
        inference_only_p50 = inference_only_times.quantile(0.50) if len(inference_only_times) > 0 else 0
        postprocess_p50 = postprocess_times.quantile(0.50) if len(postprocess_times) > 0 else 0
        detection_count_mean = detection_counts.mean() if len(detection_counts) > 0 else 0
    else:
        preprocess_p50 = 0
        inference_only_p50 = latencies.quantile(0.50) if len(latencies) > 0 else 0
        postprocess_p50 = 0
        detection_count_mean = 0

    # Boundary timing (new columns, may not exist in old CSVs)
    has_boundary = 'input_create_ms' in inference_df.columns
    if has_boundary:
        input_create_times = inference_df['input_create_ms'].dropna()
        output_copy_times = inference_df['output_copy_ms'].dropna()
        input_create_p50 = input_create_times.quantile(0.50) if len(input_create_times) > 0 else 0
        output_copy_p50 = output_copy_times.quantile(0.50) if len(output_copy_times) > 0 else 0
    else:
        input_create_p50 = 0
        output_copy_p50 = 0

    # Drift percent
    drift_percent = 0.0
    if first_30s_p50 > 0:
        drift_percent = (last_30s_p50 - first_30s_p50) / first_30s_p50 * 100

    # ORT profiling breakdown (from metadata)
    profiling_iterations = 0
    profiling_avg_total_ms = 0.0
    profiling_avg_npu_ms = 0.0
    profiling_avg_cpu_ms = 0.0
    profiling_avg_fence_ms = 0.0
    profiling_avg_overhead_ms = 0.0
    if metadata:
        try:
            profiling_iterations = int(metadata.get('profiling_iterations', 0))
            if profiling_iterations > 0:
                profiling_avg_total_ms = float(metadata.get('profiling_avg_total_ms', 0))
                profiling_avg_npu_ms = float(metadata.get('profiling_avg_npu_ms', 0))
                profiling_avg_cpu_ms = float(metadata.get('profiling_avg_cpu_ms', 0))
                profiling_avg_fence_ms = float(metadata.get('profiling_avg_fence_ms', 0))
                profiling_avg_overhead_ms = float(metadata.get('profiling_avg_overhead_ms', 0))
        except (ValueError, TypeError):
            pass

    # Pipeline benchmark results (from metadata)
    pipeline_sequential_fps = 0.0
    pipeline_pipelined_fps = 0.0
    pipeline_speedup = 0.0
    pipeline_sequential_ms = 0.0
    pipeline_pipelined_ms = 0.0
    if metadata:
        try:
            seq_fps = metadata.get('pipeline_sequential_fps', '0')
            if seq_fps and float(seq_fps) > 0:
                pipeline_sequential_fps = float(seq_fps)
                pipeline_pipelined_fps = float(metadata.get('pipeline_pipelined_fps', 0))
                pipeline_speedup = float(metadata.get('pipeline_speedup', 0))
                pipeline_sequential_ms = float(metadata.get('pipeline_sequential_ms', 0))
                pipeline_pipelined_ms = float(metadata.get('pipeline_pipelined_ms', 0))
        except (ValueError, TypeError):
            pass

    return KpiMetrics(
        # Latency (total E2E)
        latency_p50=latencies.quantile(0.50) if len(latencies) > 0 else 0,
        latency_p95=latencies.quantile(0.95) if len(latencies) > 0 else 0,
        latency_mean=latencies.mean() if len(latencies) > 0 else 0,
        latency_std=latencies.std() if len(latencies) > 0 else 0,
        latency_min=latencies.min() if len(latencies) > 0 else 0,
        latency_max=latencies.max() if len(latencies) > 0 else 0,
        inference_count=len(latencies),

        # E2E breakdown (P50)
        preprocess_p50=preprocess_p50,
        inference_only_p50=inference_only_p50,
        input_create_p50=input_create_p50,
        output_copy_p50=output_copy_p50,
        postprocess_p50=postprocess_p50,
        detection_count_mean=detection_count_mean,

        # Throughput
        fps=fps,

        # Thermal drift (E2E)
        first_30s_p50=first_30s_p50,
        last_30s_p50=last_30s_p50,
        drift_percent=drift_percent,

        # Inference-only drift
        infer_first_30s_p50=infer_first_30s_p50,
        infer_last_30s_p50=infer_last_30s_p50,
        infer_drift_percent=infer_drift_percent,

        # Thermal
        thermal_start=thermals.iloc[0] if len(thermals) > 0 else 0,
        thermal_end=thermals.iloc[-1] if len(thermals) > 0 else 0,
        thermal_max=thermals.max() if len(thermals) > 0 else 0,
        thermal_slope=thermal_slope,

        # Power
        power_mean=powers.mean() if len(powers) > 0 else 0,
        power_std=powers.std() if len(powers) > 0 else 0,

        # Memory
        memory_peak=int(memories.max()) if len(memories) > 0 else 0,
        memory_mean=memories.mean() if len(memories) > 0 else 0,
        memory_min=int(memories.min()) if len(memories) > 0 else 0,
        memory_start=int(memories.iloc[0]) if len(memories) > 0 else 0,
        memory_end=int(memories.iloc[-1]) if len(memories) > 0 else 0,

        # Duration
        duration_seconds=duration,

        # Cold start
        cold_start=cold_start,

        # ORT Profiling
        profiling_iterations=profiling_iterations,
        profiling_avg_total_ms=profiling_avg_total_ms,
        profiling_avg_npu_ms=profiling_avg_npu_ms,
        profiling_avg_cpu_ms=profiling_avg_cpu_ms,
        profiling_avg_fence_ms=profiling_avg_fence_ms,
        profiling_avg_overhead_ms=profiling_avg_overhead_ms,

        # Pipeline benchmark
        pipeline_sequential_fps=pipeline_sequential_fps,
        pipeline_pipelined_fps=pipeline_pipelined_fps,
        pipeline_speedup=pipeline_speedup,
        pipeline_sequential_ms=pipeline_sequential_ms,
        pipeline_pipelined_ms=pipeline_pipelined_ms
    )


def find_steady_state(
    df: pd.DataFrame,
    warm_up_seconds: float = 30.0
) -> pd.DataFrame:
    """
    Extract steady-state portion of the log (after warm-up period).

    Args:
        df: Full log DataFrame
        warm_up_seconds: Seconds to skip at the beginning

    Returns:
        DataFrame with only steady-state data
    """
    return df[df['elapsed_seconds'] >= warm_up_seconds].copy()


def parse_session_id(filename: str) -> dict:
    """
    Parse experiment parameters from session ID in filename.

    Expected format: kpi_log_YYYYMMDD_HHMMSS.csv
    Session ID in data: {path}_{freq}hz_{warmup}_{timestamp}

    Args:
        filename: Log filename

    Returns:
        Dict with parsed parameters
    """
    # This would need the actual session ID from within the file
    # For now, return empty dict
    return {}


def load_all_logs(directory: str) -> pd.DataFrame:
    """
    Load all CSV logs from a directory and combine them.

    Args:
        directory: Path to directory containing CSV files

    Returns:
        Combined DataFrame with 'source_file' column
    """
    path = Path(directory)
    all_dfs = []

    for csv_file in path.glob("*.csv"):
        df = load_log(str(csv_file))
        df['source_file'] = csv_file.name
        all_dfs.append(df)

    if all_dfs:
        return pd.concat(all_dfs, ignore_index=True)
    else:
        return pd.DataFrame()


def generate_single_report(file_path: str) -> Tuple[str, dict, KpiMetrics]:
    """
    Generate detailed report string for a single log file.

    Args:
        file_path: Path to CSV file

    Returns:
        Tuple of (report_string, metadata, metrics)
    """
    lines = []
    lines.append(f"Loading: {file_path}")

    # Load metadata
    metadata = load_metadata(file_path)
    if metadata:
        lines.append("\n=== Metadata ===")
        lines.append(f"  Device: {metadata.get('device_manufacturer', 'N/A')} {metadata.get('device_model', 'N/A')}")
        lines.append(f"  SoC: {metadata.get('soc_model', 'N/A')}")
        lines.append(f"  EP: {metadata.get('execution_provider', 'N/A')}")
        lines.append(f"  Model: {metadata.get('model', 'N/A')}")

    df = load_log(file_path)

    lines.append(f"\nTotal records: {len(df)}")
    lines.append(f"Duration: {df['elapsed_seconds'].max():.1f} seconds")

    metrics = calculate_metrics(df, metadata)

    # Cold Start metrics
    if metrics.cold_start:
        lines.append("\n=== Cold Start ===")
        lines.append(f"  Model Load: {metrics.cold_start.model_load_ms:.0f} ms")
        lines.append(f"  Session Create (QNN compile): {metrics.cold_start.session_create_ms:.0f} ms")
        lines.append(f"  First Inference: {metrics.cold_start.first_inference_ms:.2f} ms")
        lines.append(f"  Total Cold: {metrics.cold_start.total_cold_ms:.0f} ms")

    # Graph Partitioning (from CSV metadata)
    total_nodes = int(metadata.get('ort_total_nodes', 0)) if metadata else 0
    if total_nodes > 0:
        qnn_nodes = int(metadata.get('ort_qnn_nodes', 0))
        cpu_nodes = int(metadata.get('ort_cpu_nodes', 0))
        coverage = metadata.get('ort_coverage_percent', 'N/A')
        fallback_ops = metadata.get('ort_fallback_ops', '')
        lines.append("\n=== Graph Partitioning ===")
        lines.append(f"  Total nodes: {total_nodes}")
        lines.append(f"  QNN nodes: {qnn_nodes}")
        lines.append(f"  CPU nodes: {cpu_nodes}")
        lines.append(f"  Coverage: {coverage}%")
        if fallback_ops:
            lines.append(f"  Fallback ops: {fallback_ops.replace(';', ', ')}")

    lines.append("\n=== Sustained Performance ===")
    lines.append(f"\nE2E Latency:")
    lines.append(f"  P50: {metrics.latency_p50:.2f} ms")
    lines.append(f"  P95: {metrics.latency_p95:.2f} ms")
    lines.append(f"  Mean: {metrics.latency_mean:.2f} ms (±{metrics.latency_std:.2f})")
    lines.append(f"  Min: {metrics.latency_min:.2f} ms")
    lines.append(f"  Max: {metrics.latency_max:.2f} ms")
    lines.append(f"  Count: {metrics.inference_count}")

    if metrics.inference_only_p50 > 0:
        lines.append(f"\nE2E Breakdown (P50):")
        lines.append(f"  Preprocess:     {metrics.preprocess_p50:.2f} ms")
        lines.append(f"  Input create:   {metrics.input_create_p50:.2f} ms")
        lines.append(f"  Inference:      {metrics.inference_only_p50:.2f} ms")
        lines.append(f"  Output copy:    {metrics.output_copy_p50:.2f} ms")
        lines.append(f"  Postprocess:    {metrics.postprocess_p50:.2f} ms")
        lines.append(f"  Avg Detections: {metrics.detection_count_mean:.1f}")

    if metrics.profiling_iterations > 0:
        lines.append(f"\nORT Profiling ({metrics.profiling_iterations} iterations):")
        lines.append(f"  session.run() avg:  {metrics.profiling_avg_total_ms:.2f} ms")
        lines.append(f"  NPU compute avg:    {metrics.profiling_avg_npu_ms:.2f} ms")
        lines.append(f"  CPU compute avg:    {metrics.profiling_avg_cpu_ms:.2f} ms")
        lines.append(f"  Fence (sync) avg:   {metrics.profiling_avg_fence_ms:.2f} ms")
        lines.append(f"  ORT overhead avg:   {metrics.profiling_avg_overhead_ms:.2f} ms")
        if metrics.profiling_avg_total_ms > 0:
            npu_ratio = metrics.profiling_avg_npu_ms / metrics.profiling_avg_total_ms * 100
            lines.append(f"  NPU ratio:          {npu_ratio:.1f}%")

    if metrics.pipeline_sequential_fps > 0:
        lines.append(f"\nPipeline Benchmark:")
        lines.append(f"  Sequential:  {metrics.pipeline_sequential_ms:.2f} ms/frame ({metrics.pipeline_sequential_fps:.1f} FPS)")
        lines.append(f"  Pipelined:   {metrics.pipeline_pipelined_ms:.2f} ms/frame ({metrics.pipeline_pipelined_fps:.1f} FPS)")
        lines.append(f"  Speedup:     {metrics.pipeline_speedup:.2f}x")

    lines.append(f"\nThroughput:")
    lines.append(f"  FPS: {metrics.fps:.2f} inf/s")

    lines.append(f"\nE2E Thermal Drift:")
    lines.append(f"  First 30s P50: {metrics.first_30s_p50:.2f} ms")
    lines.append(f"  Last 30s P50: {metrics.last_30s_p50:.2f} ms")
    lines.append(f"  Drift: {metrics.drift_percent:+.1f}%")

    if metrics.infer_first_30s_p50 > 0:
        lines.append(f"\nInference-Only Drift:")
        lines.append(f"  First 30s P50: {metrics.infer_first_30s_p50:.2f} ms")
        lines.append(f"  Last 30s P50: {metrics.infer_last_30s_p50:.2f} ms")
        lines.append(f"  Drift: {metrics.infer_drift_percent:+.1f}%")

    lines.append(f"\nThermal:")
    lines.append(f"  Start: {metrics.thermal_start:.1f} °C")
    lines.append(f"  End: {metrics.thermal_end:.1f} °C")
    lines.append(f"  Max: {metrics.thermal_max:.1f} °C")
    lines.append(f"  Slope: {metrics.thermal_slope:.2f} °C/min")

    lines.append(f"\nPower:")
    lines.append(f"  Mean: {metrics.power_mean:.1f} mW (±{metrics.power_std:.1f})")

    lines.append(f"\nMemory (VmRSS):")
    lines.append(f"  Start: {metrics.memory_start} MB")
    lines.append(f"  End: {metrics.memory_end} MB")
    lines.append(f"  Peak: {metrics.memory_peak} MB")
    lines.append(f"  Mean: {metrics.memory_mean:.1f} MB")
    lines.append(f"  Delta: {metrics.memory_end - metrics.memory_start:+d} MB")

    return "\n".join(lines), metadata, metrics


def print_single_report(file_path: str):
    """Print detailed report for a single log file."""
    report, metadata, metrics = generate_single_report(file_path)
    print(report)
    return metadata, metrics


def generate_comparison_table(file_paths: list) -> str:
    """
    Generate sectioned comparison report for multiple log files.

    Args:
        file_paths: List of paths to CSV files

    Returns:
        Comparison report as string with multiple sections
    """
    import re

    # Load all data first
    experiments = []
    for file_path in file_paths:
        metadata = load_metadata(file_path)
        df = load_log(file_path)
        metrics = calculate_metrics(df, metadata)
        ort_log = load_ort_log(file_path)  # Load ORT log if available

        # Generate label: {base_model}_{precision}_{ep}
        name = Path(file_path).stem
        model_raw = metadata.get('model', 'Unknown')
        # Extract base model name (strip quantization info like "INT8 (QDQ)")
        base_model = re.sub(r'\s+INT8.*$', '', model_raw)
        ep_raw = metadata.get('execution_provider', 'CPU')
        ep_short = {'QNN_NPU': 'NPU', 'QNN_GPU': 'GPU', 'CPU': 'CPU'}.get(ep_raw, ep_raw)
        precision = metadata.get('precision', 'FP32')
        qnn_opts = metadata.get('qnn_options', '')
        if 'fp16=1' in qnn_opts and precision == 'FP32':
            precision = 'FP16'
        # Compact precision: INT8_DYNAMIC -> INT8Dyn, INT8_QDQ -> INT8QDQ
        prec_short = precision.replace('_DYNAMIC', 'Dyn').replace('_', '')
        label = f"{base_model}_{prec_short}_{ep_short}"

        experiments.append({
            'label': label,
            'name': name,
            'ep': metadata.get('execution_provider', 'N/A'),
            'model': metadata.get('model', 'N/A'),
            'precision': prec_short,
            'metrics': metrics,
            'metadata': metadata,
            'ort_log': ort_log
        })

    # Sort: FP32 first, then FP16, then INT8 variants
    prec_order = {'FP32': 0, 'FP16': 1, 'INT8QDQ': 2, 'INT8Dyn': 3, 'INT8': 4}
    experiments.sort(key=lambda e: prec_order.get(e['precision'], 9))

    lines = []
    sep = "=" * 120

    # Title
    lines.append(sep)
    lines.append("KPI Comparison Report")
    lines.append(sep)

    # Section 1: Experiment Overview
    lines.append("\n[1] Experiment Overview")
    lines.append("-" * 120)
    lines.append(f"{'#':<4} {'Label':<40} {'EP':<12} {'Precision':<12} {'Model':<25}")
    lines.append("-" * 120)
    for i, exp in enumerate(experiments, 1):
        meta = exp['metadata']
        # Determine precision from metadata
        precision = meta.get('precision', 'FP32')
        qnn_opts = meta.get('qnn_options', '')
        # Check if FP16 is enabled for NPU
        if 'fp16=1' in qnn_opts and precision == 'FP32':
            precision = 'FP16'
        lines.append(f"{i:<4} {exp['label']:<40} {exp['ep']:<12} {precision:<12} {exp['model']:<25}")
    lines.append("")
    lines.append("    EP: Execution Provider (QNN_NPU=Hexagon HTP, QNN_GPU=Adreno GPU, CPU=ARM CPU)")
    lines.append("    Precision: FP32/FP16=부동소수점, INT8=양자화 (QDQ=Static, Dynamic)")

    # Section 2: E2E Latency Performance
    lines.append(f"\n\n[2] E2E Latency Performance")
    lines.append("-" * 120)
    lines.append(f"{'#':<4} {'Label':<40} {'E2E P50(ms)':<13} {'E2E P95(ms)':<13} {'E2E Mean(ms)':<14} {'MaxFPS':<10}")
    lines.append("-" * 110)
    for i, exp in enumerate(experiments, 1):
        m = exp['metrics']
        max_fps = 1000.0 / m.latency_p50 if m.latency_p50 > 0 else 0
        lines.append(f"{i:<4} {exp['label']:<40} {m.latency_p50:<13.2f} {m.latency_p95:<13.2f} "
                     f"{m.latency_mean:<14.2f} {max_fps:<10.1f}")
    lines.append("")
    lines.append("    E2E P50/P95: 전체 파이프라인(pre+infer+post) 50th/95th percentile latency (lower=better)")
    lines.append("    MaxFPS: Theoretical max throughput = 1000/E2E P50 (higher=better)")

    # Section 2b: E2E Breakdown
    has_breakdown_data = any(exp['metrics'].inference_only_p50 > 0 for exp in experiments)
    has_boundary_data = any(exp['metrics'].input_create_p50 > 0 for exp in experiments)
    if has_breakdown_data:
        lines.append(f"\n\n[2b] E2E Breakdown (P50)")
        lines.append("-" * 140)
        if has_boundary_data:
            lines.append(f"{'#':<4} {'Label':<35} {'PreProc':<9} {'InCreate':<9} {'Infer':<9} {'OutCopy':<9} {'PostProc':<9} {'Dets':<6} {'Total':<9}")
        else:
            lines.append(f"{'#':<4} {'Label':<35} {'PreProc':<9} {'Infer':<9} {'PostProc':<9} {'Dets':<6} {'Total':<9}")
        lines.append("-" * 140)
        for i, exp in enumerate(experiments, 1):
            m = exp['metrics']
            if has_boundary_data:
                lines.append(f"{i:<4} {exp['label']:<35} {m.preprocess_p50:<9.2f} {m.input_create_p50:<9.2f} "
                             f"{m.inference_only_p50:<9.2f} {m.output_copy_p50:<9.2f} "
                             f"{m.postprocess_p50:<9.2f} {m.detection_count_mean:<6.1f} {m.latency_p50:<9.2f}")
            else:
                lines.append(f"{i:<4} {exp['label']:<35} {m.preprocess_p50:<9.2f} "
                             f"{m.inference_only_p50:<9.2f} "
                             f"{m.postprocess_p50:<9.2f} {m.detection_count_mean:<6.1f} {m.latency_p50:<9.2f}")
        lines.append("")
        lines.append("    PreProc:  Image preprocessing (letterbox + normalize + CHW)")
        if has_boundary_data:
            lines.append("    InCreate: Input tensor creation (Java→Native JNI boundary)")
        lines.append("    Infer:    Model inference only (session.run)")
        if has_boundary_data:
            lines.append("    OutCopy:  Output tensor copy (Native→Java buffer copy)")
        lines.append("    PostProc: Confidence filter + NMS + coordinate transform")

    # Section 2c: ORT Profiling (NPU compute vs framework overhead)
    has_profiling_data = any(exp['metrics'].profiling_iterations > 0 for exp in experiments)
    if has_profiling_data:
        lines.append(f"\n\n[2c] ORT Profiling (session.run Breakdown)")
        lines.append("-" * 140)
        lines.append(f"{'#':<4} {'Label':<35} {'session.run':<12} {'NPU(ms)':<10} {'CPU(ms)':<10} {'Fence(ms)':<10} {'ORT(ms)':<10} {'NPU%':<8}")
        lines.append("-" * 140)
        for i, exp in enumerate(experiments, 1):
            m = exp['metrics']
            if m.profiling_iterations > 0:
                npu_pct = m.profiling_avg_npu_ms / m.profiling_avg_total_ms * 100 if m.profiling_avg_total_ms > 0 else 0
                lines.append(f"{i:<4} {exp['label']:<35} {m.profiling_avg_total_ms:<12.2f} {m.profiling_avg_npu_ms:<10.2f} "
                             f"{m.profiling_avg_cpu_ms:<10.2f} {m.profiling_avg_fence_ms:<10.2f} "
                             f"{m.profiling_avg_overhead_ms:<10.2f} {npu_pct:<8.1f}")
            else:
                lines.append(f"{i:<4} {exp['label']:<35} {'N/A':<12} {'N/A':<10} {'N/A':<10} {'N/A':<10} {'N/A':<10} {'N/A':<8}")
        lines.append("")
        lines.append("    session.run = NPU + CPU + Fence + ORT overhead")
        lines.append("    NPU:   QNN EP 실제 연산 시간 (HTP 커널 실행)")
        lines.append("    CPU:   CPU fallback 노드 실행 시간")
        lines.append("    Fence: EP 동기화 배리어 (HTP dispatch + completion wait)")
        lines.append("    ORT:   프레임워크 오버헤드 (그래프 스케줄링, 텐서 관리, JNI)")
        lines.append("    NPU%:  session.run() 중 실제 NPU 연산 비율")

    # Section 3: Cold Start Breakdown
    lines.append(f"\n\n[3] Cold Start Breakdown")
    lines.append("-" * 120)
    lines.append(f"{'#':<4} {'Label':<40} {'Total(ms)':<12} {'Load(ms)':<12} {'Session(ms)':<12} {'1stInf(ms)':<12}")
    lines.append("-" * 120)
    for i, exp in enumerate(experiments, 1):
        m = exp['metrics']
        if m.cold_start:
            total = m.cold_start.total_cold_ms
            load = m.cold_start.model_load_ms
            session = m.cold_start.session_create_ms
            first = m.cold_start.first_inference_ms
            lines.append(f"{i:<4} {exp['label']:<40} {total:<12.0f} {load:<12.0f} {session:<12.0f} {first:<12.2f}")
        else:
            lines.append(f"{i:<4} {exp['label']:<40} {'N/A':<12} {'N/A':<12} {'N/A':<12} {'N/A':<12}")
    lines.append("")
    lines.append("    Total: 앱 시작부터 첫 추론 완료까지 = Load + Session + 1stInf")
    lines.append("    Load: ONNX 모델 파일 로드 시간")
    lines.append("    Session: ORT 세션 생성 시간 (QNN EP는 HTP 그래프 컴파일 포함)")
    lines.append("    1stInf: 첫 번째 추론 지연시간")

    # Section 4: Thermal Drift Analysis
    lines.append(f"\n\n[4] Thermal Drift Analysis (E2E Latency P50 변화)")
    lines.append("-" * 120)
    lines.append(f"{'#':<4} {'Label':<40} {'First30s(ms)':<14} {'Last30s(ms)':<14} {'Drift%':<10} {'Verdict':<16}")
    lines.append("-" * 120)
    for i, exp in enumerate(experiments, 1):
        m = exp['metrics']
        first_30s = m.first_30s_p50
        last_30s = m.last_30s_p50
        drift_pct = ((last_30s - first_30s) / first_30s * 100) if first_30s > 0 else 0

        # Verdict based on drift
        if abs(drift_pct) < 3:
            verdict = "Stable"
        elif drift_pct > 10:
            verdict = "Throttling"
        elif drift_pct > 3:
            verdict = "Slight throttle"
        elif drift_pct < -3:
            verdict = "Warmup effect"
        else:
            verdict = "Normal"

        lines.append(f"{i:<4} {exp['label']:<40} {first_30s:<14.2f} {last_30s:<14.2f} {drift_pct:<+10.1f} {verdict:<16}")
    lines.append("")
    lines.append("    First30s/Last30s: 벤치마크 처음/마지막 30초 동안의 E2E Latency P50")
    lines.append("    Drift%: (Last30s - First30s) / First30s × 100")
    lines.append("    Verdict: Stable(<±3%), Slight throttle(3~10%), Throttling(>10%), Warmup effect(<-3%)")

    # Section 4b: Inference-Only Drift Analysis
    has_infer_drift = any(exp['metrics'].infer_first_30s_p50 > 0 for exp in experiments)
    if has_infer_drift:
        lines.append(f"\n\n[4b] Inference-Only Drift Analysis (session.run P50 변화)")
        lines.append("-" * 140)
        lines.append(f"{'#':<4} {'Label':<40} {'First30s(ms)':<14} {'Last30s(ms)':<14} {'Drift%':<10} {'Verdict':<16}")
        lines.append("-" * 140)
        for i, exp in enumerate(experiments, 1):
            m = exp['metrics']
            first_30s = m.infer_first_30s_p50
            last_30s = m.infer_last_30s_p50
            drift_pct = m.infer_drift_percent

            if abs(drift_pct) < 3:
                verdict = "Stable"
            elif drift_pct > 10:
                verdict = "Throttling"
            elif drift_pct > 3:
                verdict = "Slight throttle"
            elif drift_pct < -3:
                verdict = "Warmup effect"
            else:
                verdict = "Normal"

            lines.append(f"{i:<4} {exp['label']:<40} {first_30s:<14.2f} {last_30s:<14.2f} {drift_pct:<+10.1f} {verdict:<16}")
        lines.append("")
        lines.append("    First30s/Last30s: 벤치마크 처음/마지막 30초 동안의 Inference-only (session.run) P50")
        lines.append("    E2E Drift와 비교하여 inference 자체의 sustained 성능 변화를 분리 관찰")

    # Section 5: System Resources
    lines.append(f"\n\n[5] System Resources")
    lines.append("-" * 120)
    lines.append(f"{'#':<4} {'Label':<40} {'Power(mW)':<12} {'Slope(°C/min)':<14} {'MemPeak(MB)':<12}")
    lines.append("-" * 120)
    for i, exp in enumerate(experiments, 1):
        m = exp['metrics']
        lines.append(f"{i:<4} {exp['label']:<40} {m.power_mean:<12.1f} {m.thermal_slope:<14.2f} {m.memory_peak:<12}")
    lines.append("")
    lines.append("    Power: 평균 전력 소비량 (mW)")
    lines.append("    Slope: 온도 상승률 (°C/min, lower=better)")
    lines.append("    MemPeak: 최대 메모리 사용량 (MB)")

    # Section 5b: Memory Analysis
    lines.append(f"\n\n[5b] Memory Analysis (VmRSS)")
    lines.append("-" * 120)
    lines.append(f"{'#':<4} {'Label':<40} {'Start(MB)':<10} {'End(MB)':<10} {'Peak(MB)':<10} {'Mean(MB)':<10} {'Delta(MB)':<10} {'Verdict':<16}")
    lines.append("-" * 120)
    for i, exp in enumerate(experiments, 1):
        m = exp['metrics']
        delta = m.memory_end - m.memory_start
        if m.memory_start > 0 and abs(delta) / m.memory_start * 100 > 10:
            verdict = "Leak risk" if delta > 0 else "Shrinking"
        elif delta > 20:
            verdict = "Growing"
        elif delta < -20:
            verdict = "Shrinking"
        else:
            verdict = "Stable"
        lines.append(f"{i:<4} {exp['label']:<40} {m.memory_start:<10} {m.memory_end:<10} "
                     f"{m.memory_peak:<10} {m.memory_mean:<10.0f} {delta:<+10} {verdict:<16}")
    lines.append("")
    lines.append("    Start/End: 벤치마크 시작/종료 시점의 VmRSS")
    lines.append("    Delta: End - Start (양수=메모리 증가, 음수=감소)")
    lines.append("    Verdict: Stable(±20MB 이내), Growing/Shrinking(>20MB), Leak risk(>10% 증가)")

    # Section 6: Model Details
    lines.append(f"\n\n[6] Model Details")
    lines.append("-" * 120)
    lines.append(f"{'#':<4} {'Label':<40} {'Size(KB)':<12} {'Input Shape':<24} {'QNN Options':<30}")
    lines.append("-" * 120)
    for i, exp in enumerate(experiments, 1):
        meta = exp['metadata']
        size_kb = meta.get('model_size_kb', 'N/A')
        input_shape = meta.get('input_shape', 'N/A')
        qnn_opts = meta.get('qnn_options', 'N/A')
        lines.append(f"{i:<4} {exp['label']:<40} {size_kb:<12} {input_shape:<24} {qnn_opts:<30}")
    lines.append("")
    lines.append("    Size: 모델 파일 크기 (KB)")
    lines.append("    Input Shape: 입력 텐서 shape [N,C,H,W]")
    lines.append("    QNN Options: QNN Execution Provider 옵션 (NPU/GPU 사용시)")
    # Section 7: Graph Partitioning & Coverage
    # Try CSV metadata first, then fall back to ORT log files
    has_partition_data = any(
        exp.get('ort_log') or exp['metadata'].get('ort_total_nodes', '0') != '0'
        for exp in experiments
    )
    if has_partition_data:
        lines.append(f"\n\n[7] Graph Partitioning & Coverage")
        lines.append("-" * 120)
        lines.append(f"{'#':<4} {'Label':<40} {'Total':<8} {'QNN':<8} {'CPU':<8} {'Coverage':<10} {'Fallback Ops':<40}")
        lines.append("-" * 120)
        for i, exp in enumerate(experiments, 1):
            meta = exp['metadata']
            ort = exp.get('ort_log')

            # Prefer CSV metadata (embedded by app), fall back to ORT log
            total = int(meta.get('ort_total_nodes', 0))
            qnn = int(meta.get('ort_qnn_nodes', 0))
            cpu = int(meta.get('ort_cpu_nodes', 0))
            fallback_ops_str = meta.get('ort_fallback_ops', '')

            if total == 0 and ort:
                total = ort.get('total_nodes', 0)
                qnn = ort.get('qnn_nodes', 0)
                cpu = ort.get('cpu_nodes', 0)
                fallback_ops_str = ', '.join(ort.get('fallback_ops', []))

            coverage = f"{qnn/total*100:.1f}%" if total > 0 else "N/A"
            fallback_display = fallback_ops_str.replace(';', ', ')[:40] if fallback_ops_str else '-'

            lines.append(f"{i:<4} {exp['label']:<40} {total:<8} {qnn:<8} {cpu:<8} {coverage:<10} {fallback_display:<40}")
        lines.append("")
        lines.append("    Total: 그래프 총 노드 수")
        lines.append("    QNN: QNN EP에서 실행되는 노드 수 (NPU/GPU)")
        lines.append("    CPU: CPU fallback 노드 수")
        lines.append("    Coverage: QNN 노드 비율 (QNN/Total × 100)")
        lines.append("    Fallback Ops: CPU로 fallback된 연산 목록")

    # Section 8: Coverage vs E2E Analysis
    # Only show when multiple experiments with partition data exist
    exps_with_coverage = []
    for exp in experiments:
        meta = exp['metadata']
        total = int(meta.get('ort_total_nodes', 0))
        ort = exp.get('ort_log')
        if total == 0 and ort:
            total = ort.get('total_nodes', 0)
        if total > 0:
            qnn = int(meta.get('ort_qnn_nodes', 0))
            if qnn == 0 and ort:
                qnn = ort.get('qnn_nodes', 0)
            coverage_pct = qnn / total * 100
            exps_with_coverage.append((exp, coverage_pct))

    if len(exps_with_coverage) >= 2:
        lines.append(f"\n\n[8] Coverage vs E2E Analysis")
        lines.append("-" * 120)
        lines.append(f"{'#':<4} {'Label':<40} {'Coverage%':<12} {'E2E P50':<10} {'Infer P50':<10} {'Pre+Post':<10} {'Drift%':<10}")
        lines.append("-" * 120)

        # Find CPU baseline for comparison
        cpu_exp = None
        for exp, cov in exps_with_coverage:
            if exp['ep'] == 'CPU' or cov == 0:
                cpu_exp = exp
                break

        for i, (exp, cov) in enumerate(exps_with_coverage, 1):
            m = exp['metrics']
            pre_post = m.preprocess_p50 + m.postprocess_p50
            lines.append(f"{i:<4} {exp['label']:<40} {cov:<12.1f} {m.latency_p50:<10.2f} "
                         f"{m.inference_only_p50:<10.2f} {pre_post:<10.2f} {m.drift_percent:<+10.1f}")

        lines.append("")
        lines.append("    Coverage%: QNN offload 비율")
        lines.append("    E2E P50: 전체 파이프라인 P50 latency (ms)")
        lines.append("    Infer P50: 순수 추론 P50 (EP에 의해 가속)")
        lines.append("    Pre+Post: 전후처리 합계 P50 (항상 CPU)")
        lines.append("    Drift%: Sustained 성능 변화율 (first 30s → last 30s)")

        if cpu_exp:
            lines.append("")
            lines.append("    * CPU baseline 대비 E2E 감소율:")
            cpu_e2e = cpu_exp['metrics'].latency_p50
            for exp, cov in exps_with_coverage:
                if exp != cpu_exp and cpu_e2e > 0:
                    reduction = (cpu_e2e - exp['metrics'].latency_p50) / cpu_e2e * 100
                    lines.append(f"      {exp['label']}: Coverage {cov:.1f}% → E2E {reduction:+.1f}% 감소")

    # Section 9: Pipeline Throughput Analysis
    has_pipeline_data = any(exp['metrics'].pipeline_sequential_fps > 0 for exp in experiments)
    if has_pipeline_data:
        lines.append(f"\n\n[9] Pipeline Throughput Analysis")
        lines.append("-" * 140)
        lines.append(f"{'#':<4} {'Label':<35} {'Seq(ms)':<10} {'Pipe(ms)':<10} {'SeqFPS':<10} {'PipeFPS':<10} {'Speedup':<10} {'TheoFPS':<10}")
        lines.append("-" * 140)
        for i, exp in enumerate(experiments, 1):
            m = exp['metrics']
            if m.pipeline_sequential_fps > 0:
                # Theoretical max: limited by max(infer, pre+post)
                cpu_work = m.preprocess_p50 + m.input_create_p50 + m.output_copy_p50 + m.postprocess_p50
                bottleneck = max(cpu_work, m.inference_only_p50)
                theo_fps = 1000.0 / bottleneck if bottleneck > 0 else 0
                lines.append(f"{i:<4} {exp['label']:<35} {m.pipeline_sequential_ms:<10.2f} {m.pipeline_pipelined_ms:<10.2f} "
                             f"{m.pipeline_sequential_fps:<10.1f} {m.pipeline_pipelined_fps:<10.1f} "
                             f"{m.pipeline_speedup:<10.2f} {theo_fps:<10.1f}")
            else:
                lines.append(f"{i:<4} {exp['label']:<35} {'N/A':<10} {'N/A':<10} {'N/A':<10} {'N/A':<10} {'N/A':<10} {'N/A':<10}")
        lines.append("")
        lines.append("    Seq:     순차 실행 (pre→infer→post) 평균 시간")
        lines.append("    Pipe:    파이프라인 실행 (pre+post와 infer 병렬화) 평균 시간")
        lines.append("    Speedup: Pipe/Seq 실측 속도 향상")
        lines.append("    TheoFPS: 이론적 최대 = 1000/max(CPU작업, Infer)")
        lines.append("    * 실측 < 이론: 스레드 동기화, 큐잉, GC 등의 오버헤드")

    lines.append("")
    return "\n".join(lines)


def print_comparison_table(file_paths: list):
    """Print comparison table for multiple log files."""
    report = generate_comparison_table(file_paths)
    print(report)


if __name__ == "__main__":
    import sys
    import argparse
    from datetime import datetime

    parser = argparse.ArgumentParser(description="Parse and analyze KPI log files")
    parser.add_argument("paths", nargs="+", help="Log files or directories to analyze")
    parser.add_argument("--compare", "-c", action="store_true", help="Show comparison table")
    parser.add_argument("--output", "-o", help="Output file path (txt). If not specified, auto-generates in outputs folder")
    parser.add_argument("--output-dir", "-d", help="Output directory (default: outputs/ in project root)")
    parser.add_argument("--print", "-p", action="store_true", help="Print to console instead of saving to file")

    args = parser.parse_args()

    # Collect all log files
    log_files = []
    input_dir = None
    for p in args.paths:
        path = Path(p)
        if path.is_dir():
            input_dir = path
            # Search for CSV files in the specified directory only (not subdirectories)
            log_files.extend(sorted(path.glob("kpi_*.csv")))
        elif path.exists():
            if input_dir is None:
                input_dir = path.parent
            log_files.append(path)
        else:
            print(f"Warning: {p} not found")

    if not log_files:
        print("No log files found")
        sys.exit(1)

    header = f"Found {len(log_files)} log file(s)\n"

    # Generate report
    is_comparison = args.compare or len(log_files) > 1
    if is_comparison:
        report = generate_comparison_table([str(f) for f in log_files])
    else:
        report, _, _ = generate_single_report(str(log_files[0]))

    full_report = header + report

    # Determine output path
    if args.print:
        # Print to console
        print(full_report)
    else:
        # Save to file
        if args.output:
            output_path = Path(args.output)
        else:
            # Determine output directory
            if args.output_dir:
                output_dir = Path(args.output_dir)
            else:
                # Default: outputs/ folder in project root (relative to script location)
                script_dir = Path(__file__).parent
                project_root = script_dir.parent.parent
                output_dir = project_root / "outputs"

            output_dir.mkdir(parents=True, exist_ok=True)

            # Generate output filename based on input folder name
            folder_name = input_dir.name if input_dir else "logs"
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            if is_comparison:
                output_path = output_dir / f"{folder_name}_comparison_{timestamp}.txt"
            else:
                output_path = output_dir / f"{log_files[0].stem}_report.txt"

        output_path.write_text(full_report, encoding='utf-8')
        print(f"Report saved to: {output_path}")
